version: '3.5'

services:
  php-apache:
    image: diazdavid/dev-apache-php-7.4.3:latest
    container_name: php-mowers-seat
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9013 remote_enable=1
    networks:
      - mowers-seat

networks:
  mowers-seat:
    name: mowers-seat
